### ISSUE TITLE
Can´t connect - Node red reboots

### ISSUE THREAD

**Issue by rosiste** [PizlaTheDeveloper/Foxtrot-Node-Red#1]
Hi, trying to implement working PLCComS communication server into my Node Red automation and following error reboots Node Red container if I try to use Foxtrot Input node:

14 Jan 23:25:57 - [red] Uncaught Exception:
14 Jan 23:25:57 - TypeError: Cannot read property 'split' of undefined
    at responses.forEach.element (/config/node-red/node_modules/node-red-contrib-foxtrotnode/foxtrot.js:272:51)
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/config/node-red/node_modules/node-red-contrib-foxtrotnode/foxtrot.js:268:23)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)

**Comment by PizlaTheDeveloper** [comment]
Should be fixed by 0633762a49e8b0086c47377397f7b866d3d04b78
